<!-- Google tag (gtag.js)-->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>
```
# Lipídios

|       Para este capítulo algumas das estruturas não estão disponíveis no banco de dados que renderiza as estruturas tridimensionais, a partir do sítio [Cactus](https://cactus.nci.nih.gov/chemical/structure){target="_blank"}, fonte de modelos do *JSmol* pelo portal do [Stolaff College](https://chemapps.stolaf.edu/jmol/jmol.php?model=water&script=Console){target="_blank"}. Entretanto, essas estruturas serão disponibilizadas como imagens *PNG* passíveis de renderização pelo *Jmol/JSmol*.

## Ácidos graxos e derivados

|       Lipídios podem apresentar-se basicamente em dois tipos: como **hidrocarbonetos**\index{hidrocarboneto} formados por conjugação de etilenos para derivados carboxílicos de hidrocarbonetos (derivados de acetatos), ou por **esteroides**\index{esteroide}, estruturas de quatro aneis hidrófobos fundidos e derivados de isoprenos. O [ácido palmítico](https://chemapps.stolaf.edu/jmol/jmol.php?model=palmitate&script=Console){target="_blank"} exemplifica o primeiro tipo. Todo ácido graxo é formado por uma "cauda" de hidrocarboneto ou cadeia alquila, e uma "cabeça" de ácido carboxílico. O carbono do grupo carboxílico é numerado como *C1* ou carbono $\alpha$, e o último carbono da cadeia, como carbono $\omega$. Por apresentar um valor de pKa em torno de 4,8 a 7,7 (proporcional ao tamanho da cadeia carbônica) os ácidos graxos tendem a apresentar-se parcialmente ionizados em solução fisiológica.

### Insaturação e nomenclatura de ácidos graxos

|       Ácidos graxos podem diferir em tamanho (número de carbonos) e grau de insaturação. O [ácido palmítico](https://chemapps.stolaf.edu/jmol/jmol.php?model=palmitate&script=Console){target="_blank"} representa um ácido graxo com ligações saturadas, o que lhe classifica com um \index{ácido graxo saturado}**ácido graxo saturado**. A inserção de uma ligação dupla limita a flexibilidade da cadeia alquila nessa região, e promove uma alteração conformacional que reduz sua capacidade de adesão entre moléculas. Dessa forma exemplifica-se o [ácido oleico](https://chemapps.stolaf.edu/jmol/jmol.php?model=oleate&script=Console){target="_blank"}, um **ácido graxo insaturado**\index{ácido graxo insaturado} de 18 carbonos (C-18).

|       A área ocupada por um ácido graxo insaturado também é maior, 32 Å$^{2}$ para o ácido oleico\index{ácido oleico}, enquanto o ácido esteárico, também um C-18 , embora saturado, apresenta 21 Å$^{2}$. Cada dupla ligação inserida na estrutura de um ácido graxo altera sua conformação local, como exemplificado para o [ácido linolênico](https://chemapps.stolaf.edu/jmol/jmol.php?model=linoleate&script=Console){target="_blank"}\index{ácido linolênico}, com três duplas ligações em sua estrutura.

|   As insaturações também dão origem a dois *isômeros configuracionais*, *cis* e *trans*\index{configuração cis e trans}, dependentes do posicionamento dos átomos de hidrogênios, se opostos na dupla ligação (*trans*) ou próximos e ao mesmo lado desta (*cis*). Assim, ácidos graxos *cis* exibem a ligação dos hidrogênios HC=CH na mesma direção ([ácido linolênico](https://chemapps.stolaf.edu/jmol/jmol.php?model=linoleate&script=Console){target="_blank"}, C18, ácido linolênico), ao passo que *ácidos graxos trans* o fazem em direções contrárias. Daí o nome **gordura trans**\index{gordura trans} presente em produtos industrializados e utraprocessdos, e relacionada à disfunções clínicas, como aterosclerose e complicações cardíacas.

|       Por possuir a primeira dupla ligação no 3o. carbono contado a partir do último carbono da cadeia (carbono $\omega$), o ácido linolênico\index{ácido $\alpha$-linolênico} também é denominado por $\omega$-3. Essa nomenclatura permite diferenciar o \index{ácido $\alpha$-linolênico}ácido $\alpha$-linolênico, um $\omega$-3, do \index{ácido $\gamma$-linolênico}$\gamma$-linolênico, um $\omega$-6. E por essa nomenclatura, o [ácido oleico](https://chemapps.stolaf.edu/jmol/jmol.php?model=oleate&script=Console){target="_blank"} é considerado um ácido graxo da série $\omega$-9.

|       Existem dois ácidos tidos como **ácidos graxos essenciais**\index{ácido graxo essencial}, ou seja, que necessitam ingestão uma vez que não são produzidos em mamíferos, um $\omega$-3, ácido linolênico, e um $\omega$-6, ácido linoleico.\index{série ômega}.

|       Uma nomenclatura mais técnica, e que evita sinonímias estruturais, é a que define a posição de cada dupla ligação na estrutura. Dessa forma o ácido linolênico é denominado por 18:3$^{\Delta~ 9,12,15}$, enquanto que o ácido linoleico exibe o código 18:2$^{\Delta~ 9,12}$.

### Reações químicas de ácidos graxos

|       Ácidos graxos podem sofrer três transformações principais: **rancificação**\index{rancificação}, **hidrogenação**\index{hidrogenação} e **saponificação**\index{saponificação}. A **rancificação** decorre da ação do oxigênio molecular, temperatura elevada e/ou de microorganismos sobre as insaturações, promovendo clivagem do ácido graxo e liberação de derivados graxos de baixo peso molecular, por vezes voláteis, e com odor desagradável. Já a hidrogenação\* envolve um processo industrial sobre as ligações insaturadas, tornando-as saturadas.

|       A *saponificação*, por sua vez, ocorre quando um álcali forte, como NaOH ou KOH interage com uma estrutura mais complexa de ácidos graxos, os triglicerídios, triglicérides ou, mais apropriadamente, \index{triacilglicerol}[triacilglicerois](https://chemapps.stolaf.edu/jmol/jmol.php?model=triglyceride&script=Console){target="_blank"}. Esses são formados por uma ligação éster a cada um dos três ácidos graxos ao álcool glicerol, como exemplificado para a [trimiristina](./figuras/trimiristina.png){target="_blank"}. Em suma, a saponificação produz estrutruras anfipáticas polares na extremidade de interação do carboxilato com íons sódio ou potássio, o que permite sua interação com água, ao mesmo tempo que as caudas apolares permitem interação com estruturas lipídicas, promovendo uma redução da tensão superficial da água em torno da molécula-alvo e, mais grosseiramente, a limpeza de gorduras.

|       Dessa forma, na saponificação, a hidrólise alcalina do triglicerídio libera o [glicerol](https://chemapps.stolaf.edu/jmol/jmol.php?model=glycerol&script=Console){target="_blank"} e forma uma mistura de sais de ácidos graxos livres com seus carboxilatos ionizados em interação com o cátion do álcali (Na$^{+}$ ou K$^{+}$).

### Outros derivados

|       Outras estruturas derivadas de ácidos graxos incluem os **fosfolipídios**\index{fosfolipídios}, **esfingolipídios**\index{esfingolipídios} e **glicolipídios**\index{glicolipídios}. Desses, os *fosfolipídios* são mais comuns e presentes na estrutura de biomembranas\index{biomembranas}, como a *lecitina*. A lecitina é na verdade um composto lipídico amarelado, formado por misturas de [fosfatidilcolina](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylcholine&script=Console){target="_blank"}, [fosfatidilserina](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylserine&script=Console){target="_blank"}, [fosfatidiletanolamina](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylethanolamine&script=Console){target="_blank"}, [ác. fosfatídico](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidate&script=Console){target="_blank"} e *fosfatidilinositol*, um derivado do [inositol](https://chemapps.stolaf.edu/jmol/jmol.php?model=inositol&script=Console){target="_blank"}. Mas a [lecitina](./figuras/lecitina.png){target="_blank"} também pode considerar-se isoladamente como uma molécula de 1-hexadecanoil-2-(9Z,12Z-octadecadienoil)-sn-glicero-3-fosfocolina, uma fosfatidilcolina\index{fosfatidilcolina}. A [colina](https://chemapps.stolaf.edu/jmol/jmol.php?model=choline&script=Console){target="_blank"}, 2-hidroxietil-trimetilamônio, aparece como a estrutura aminada ligada ao grupo fosfato.

|       **Esfingolipídios**, fosfolipídios encontrados com frequência em membranas celulares, como a bainha de mielina de axônios, possuem uma estrutura de ancoramento a ácidos graxos distinto do glicerol, a [esfingosina](https://chemapps.stolaf.edu/jmol/jmol.php?model=sphingosine&script=Console){target="_blank"}(D-eritro-esfingosina). Um exemplo é a *esfingomielina*, usualmente formado por [fosfocolina](https://chemapps.stolaf.edu/jmol/jmol.php?model=%20phosphocholine&script=Console){target="_blank"} e [ceramida](https://chemapps.stolaf.edu/jmol/jmol.php?model=%20ceramide&script=Console){target="_blank"} ou [fosfatidiletanolamina](https://chemapps.stolaf.edu/jmol/jmol.php?model=phosphatidylethanolamine&script=Console){target="_blank"}. Não obstante, há referências também para uma estrutura única da [esfingomielina](./figuras/esfingomielina.png){target="_blank"}\index{esfingomielina}.
|       A [ceramida](https://chemapps.stolaf.edu/jmol/jmol.php?model=%20ceramide&script=Console){target="_blank"} também é encontrada na casca de frutas como a maçã, no cerume de ouvido, e na produção do mel. Ceramidas inibem a evaporação de água além de atuar fisiologicamente na regulação celular.
|       Por fim, **glicolipídios** constituem lipídios com uma ligação covalente a um monossacarídio, como o *cerebrosídio*, mantém a estabilidade estrutural da membrana e facilitam o reconhecimento celular.

## Associação de ácidos graxos

|       Lipídios, tais como ácidos graxos, fosfolipídios ou esfingolipídios, podem sofrer auto-associação em solventes aquosos (sangue, por exemplo), levando à formação de estruturas como *lipossomos*\index{lipossomo}, [micelas](./figuras/micela.png){target="_blank"}\index{micela}, e [membranas biológicas](./figuras/membrana.png){target="_blank"}\index{biomembrana}. Observe que em todas essas associações a água mantém sua interação com a face polar da estrutura, como exemplificado nas Figuras\~\ref{micela2} e \~\ref{membr}. Em *micelas reversas*\index{micelas reversas}, por outro lado, ocorre o contrário, quando em contato com solvente. Já a [membrana biológica](./figuras/membrana.png){target="_blank"} como bicamada lipídica contendo fosfolipídios, também apresenta colesterol entre as cadeias alifáticas de fosfo e esfingolipídios, o que permite reduzir o efeito de paracristalinidade com a temperatura, bem como um extenso conjunto de proteínas integrais e periféricas, informações essas não disponíveis no modelo estrutural.

## Derivados vitamínicos e da homeostasia inflamatória

### Vitaminas lipossolúveis

|       A partir de cadeias alifáticas de 20 carbonos diversos compostos são produzidos, gerando um grupo denominado **eicosanóides**\index{eicosanoide} *eicoso*, do grego, vinte). Desse grupo, algumas vitaminas são tomadas por exemplos, tais como o [retinol](https://chemapps.stolaf.edu/jmol/jmol.php?model=retinol&script=Console){target="_blank"} ou *vitamina A*\index{vitamina A}, e o [tocoferol](https://chemapps.stolaf.edu/jmol/jmol.php?model=tocopherol&script=Console){target="_blank"} ou *vitamina E*\index{vitamina E}.

### Mediadores da inflamação

|       De mesmo modo, compostos do equilíbrio da inflamação também são sintetizados a partir de precursores lipídicos, em especial do [ácido araquidônico](https://chemapps.stolaf.edu/jmol/jmol.php?model=arachidonate&script=Console){target="_blank"}\index{ác. araquidônico}, tais como [prostaglandinas](https://chemapps.stolaf.edu/jmol/jmol.php?model=prostaglandin&script=Console){target="_blank"}\index{prostaglandina}, [leucotrienos](./figuras/leucotrienoB4.png){target="_blank"}\index{leucotrieno}, e [tromboxanos](./figuras/tromboxano.png){target="_blank"}\index{tromboxano}.

## Esteróides

|       O segundo grande conjunto de lipídios deriva da ligação sobreposta de [isoprenos](https://chemapps.stolaf.edu/jmol/jmol.php?model=isoprene&script=Console){target="_blank"}\index{isopreno}, estruturas de *5C* e que formam uma molécula esteroidal denominada [colesterol](https://chemapps.stolaf.edu/jmol/jmol.php?model=cholesterol&script=Console){target="_blank"}\index{colesterol}. Quimicamente o colesterol é um álcool formado a partir da fusão de quatro aneis formados por *isoprenoides*, produzindo um anel de *peridrociclofenantreno*\index{peridrociclofenantreno}. Quando em alto teor, o colesterol pode originar [cristais de colesterol](./figuras/colesterol-cristal.png){target="_blank"}\index{cristal de colesterol} por *efeito hidrofóbico* entre suas moléculas, excluindo o solvente aquoso.

### Derivados do colesterol

|       A partir do colesterol são biossintetizadas diversas estruturas esteroidais que incluem *hormônios sexuais* como [testosterona](https://chemapps.stolaf.edu/jmol/jmol.php?model=testosterone&script=Console){target="_blank"}\index{testosterona} (ou 17-hidroxi-androst-4-en-3-ona, um C21), [progesterona](https://chemapps.stolaf.edu/jmol/jmol.php?model=progesterone&script=Console){target="_blank"}\index{progesterona}, e [estradiol](https://chemapps.stolaf.edu/jmol/jmol.php?model=estradiol&script=Console){target="_blank"}\index{estradiol}. Também são produzidos *mineralocorticoides*, tais como a [aldosterona](https://chemapps.stolaf.edu/jmol/jmol.php?model=aldosterone&script=Console){target="_blank"}\index{aldosterona} (também conhecido por 11,21-dihidroxi-3,20-dioxo-pregn-4-en-18-al, um C21, para controle de sódio sanguíneo), [cortisol](https://chemapps.stolaf.edu/jmol/jmol.php?model=cortisol&script=Console){target="_blank"}\index{cortisol} (quimicamente, 11,17,21-trihidroxipregn-4-eno-3,20-diona, ativo no catabolismo celular), *vitaminas lipossolúveis* como a [vitamina D](https://chemapps.stolaf.edu/jmol/jmol.php?model=calciferol&script=Console){target="_blank"}\index{vitamina D} (calciferol ou 7-dehidrocolecalciferol, regulação do cálcio) e a [vitamina K](https://chemapps.stolaf.edu/jmol/jmol.php?model=phylloquinone&script=Console){target="_blank"}\index{vitamina K} (ou filoquinona, presente na coagulação sanguínea), e *ácidos biliares* (emulsificantes lipídicos), como o [ácido cólico](https://chemapps.stolaf.edu/jmol/jmol.php?model=cholate&script=Console){target="_blank"}\index{ác. cólico}, [ácido deoxicólico](https://chemapps.stolaf.edu/jmol/jmol.php?model=deoxycholate&script=Console){target="_blank"}\index{ác. deoxicólico}, e o [ácido taurocólico](https://chemapps.stolaf.edu/jmol/jmol.php?model=taurocholate&script=Console){target="_blank"}\index{ác. taurocólico}, esse derivado da [taurina](https://chemapps.stolaf.edu/jmol/jmol.php?model=taurine&script=Console){target="_blank"}\index{taurina}.
