<!-- Google tag (gtag.js)--> 
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1L73VGCG5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S1L73VGCG5');
</script>

# Peptídios

## Estrutura

|       Observe a estrutura do peptídio [Gly-Cys](https://chemapps.stolaf.edu/jmol/jmol.php?model=C(C(C(=O)O)NC(=O)CN)S&script=Console){target="\_blank"}. Trata-se de um dipeptídio formado por uma *ligação peptídica* (ou *amida*) entre um resíduo de *Glicina* e outro de *Cisteína.*

|       Assim como renderizado pelo *JSmol* como um *applet* para internete, moléculas variadas podem ser carregadas pelo *Jmol* instalado no computador, como mencionado no capítulo sobre *Aminoácidos*. Caso a estrutura desejada não seja encontrada por aqueles métodos, pode-se obtê-la por carregamento de seu código *SMILES (Simplified Molecular Input Line Entry System)*, uma notação química simplificada. Alguns sítios apresentam o código SMILES de compostos, entre os quais o [PubChem](https://pubchem.ncbi.nlm.nih.gov/). Assim, para o dipeptídio *Gly-Cys* acima, pode-se carregar a estrutura no *Jmol* (ou mesmo do *JSmol*) a partir do *Console*, digitando seu código *SMILES*, como segue:

```{}
load $C(C(C(=O)O)NC(=O)CN)S
```

|       Também se pode obter o nome da molécula em estudo neste material ou seu código *SMILES* de modo até mais simples: basta passar o mouse no *hiperlink* que contém o nome da molécula e observar sua chamada (*model=*) na parte inferior da janela do navegador.
|       Comandos digitados para observações específicas podem ser efetuados em qualquer dos dois ambientes (*Jmol* ou *JSmol*). Exemplificando-se, tente uma representação mais simples para estrutura:

```{}
 wireframe only; wireframe 50; color cpk
 # e em seguida...
 cpk only;color translucent # cpk ou spacefill, modelo de preenchimento
 ```


|       Retorne para a visualização da estrutura como varetas (*wireframe*), e identifique as *cadeias laterais* de ambos os resíduos, um -H para Gly e -CH$_{2}$-SH para Cys. Identifique também a *ligação peptídica*\index{ligação peptídica} (amida formada entre o carboxilato de um aminoácido e o grupo amina do seguinte). Esta ligação *C-N* estará entre uma carbonila (-C=O) e uma amina (-NH) do *esqueleto carbônico* do modelo.

|       Visualize agora outro peptídio, a [cistina](https://chemapps.stolaf.edu/jmol/jmol.php?model=cystine&script=Console){target="\_blank"}, quer pelo *link* fornecido, ou pelo código *SMILES* obtido para o *Jmol* ou *JSmol*. Observe quais aminoácidos o definem e veja que a ligação entre eles não é peptídica. Na verdade, formam uma **ligação dissulfeto**\index{ligação dissulfeto}, típica da conformação de proteínas.

|       A visualização dessas estruturas carregadas nem sempre está otimizada, sob o ponto de vista energético. Nesse sentido, o *Jmol/JSmol* possui um algoritmo para otimização de estruturas\index{otimização estrutural}. Pra evidenciar isso, clique com o botão direito do mouse próximo à molécula e selecione *Computation, Optimize structure*. A dinâmica dos ajustes observados segue automaticamente dois *campos de forças*, MMFF94 ou UFF, dependendo do reconhecimento atômico (vide a [documentação de scrip](https://chemapps.stolaf.edu/jmol/docs/#minimize){target="_blank"} disponível).

## Peptídios bioativos

|       Agora experimente observação de alguns peptídios de importância metabólica. Para isso, carregue a [glutationa](https://chemapps.stolaf.edu/jmol/jmol.php?model=glutathione&script=Console){target="_blank"}, um dos principais antioxidantes intracelulares, função conferida essencialmente pelo grupo tiol do tripeptídio (glutamilcisteinilglicina). Mais fácil agora a identificação das ligações peptídicas ? 

|       Para outros peptídios de importância observe a [creatina](https://chemapps.stolaf.edu/jmol/jmol.php?model=creatine&script=Console){target="_blank"} e depois a [carnitina](https://chemapps.stolaf.edu/jmol/jmol.php?model=carnitine&script=Console){target="_blank"}. Compare ambas as estruturas e observe de quais aminoácidos são derivadas.

|       Visualize também a estrutura do dipeptídio sintético [aspartame](https://chemapps.stolaf.edu/jmol/jmol.php?model=aspartame&script=Console){target="_blank"}, um éster metílico de aspartil-fenilalanina largamente utilizado como adoçante. Por sua estrutura, reflita sobre o motivo pelo qual pessoas que possuem deficiência na enzima *fenilalanina hidroxilase* (diagnosticada pelo "teste do pezinho") não podem consumi-lo.

## Ligação Peptídica

|       Localize os principais *ângulos diedrais* \index{ângulo diedral} $\phi$ (*phi*) e $\psi$ (*psi*) na estrutura do dipeptídio [Gly-Cys](https://chemapps.stolaf.edu/jmol/jmol.php?model=C(C(C(=O)O)NC(=O)CN)S&script=Console){target="\_blank"} observado anteriormente (mas saiba que existem ainda os ângulos diedrais $\omega$-*ômega* e $\chi$-*chi*). O ângulo *phi* descreve a rotação na ligação N-C($\alpha$) do grupo C(O)-N-C($\alpha$)-C(O), enquanto o ângulo *psi* descreve a rotação da ligação C($\alpha$)-C(O) no grupo N-C($\alpha$)-C(O)-N da ligação peptídica.


|       Difícil ? Resumindo: a partir da ligação peptídica C-N, *phi* é o ângulo que "desponta" do N e *psi* o que "sai" do C. Ainda com problemas ?  Para facilitar, identifique os átomos do modelo por:

```{}
label %a
```

|       A ligação peptídica é apresentada entre os átomos *C7* e *N6*. 